dsa::eAlloc Class Reference
A memory allocator class based on the Two-Level Segregated Fit (TLSF) algorithm.
#include <eAlloc.hpp>
Classes
struct IntegrityResult
Structure to hold integrity check results.
struct StorageReport
Structure to report storage usage statistics.
Public Types
using tlsf = dsa::TLSF<5>
TLSF allocator with 32 second-level lists.
using Control = tlsf::Control
TLSF control structure type.
using BlockHeader = tlsf::BlockHeader
TLSF block header type.
using Walker = tlsf::tlsf_walker
Function type for walking memory blocks.
Public Member Functions
void setLock (glock::ILockable *lock)
eAlloc (void *mem, size_t bytes)
Constructs an eAlloc instance with an initial memory pool.
void * malloc (size_t size)
Allocates a block of memory of the specified size.
void free (void *ptr)
Frees a previously allocated memory block.
void * memalign (size_t align, size_t size)
Allocates a memory block with specified alignment and size.
void * realloc (void *ptr, size_t size)
Reallocates a memory block to a new size.
void * calloc (size_t num, size_t size)
Allocates memory for an array and initializes it to zero.
template<typename T>
T * allocate (const T &obj)
Allocates memory for an object and constructs it by copying.
template<typename T, typename... Args>
T * allocate (Args &&... args)
Allocates memory for an object and constructs it with arguments.
template<typename T>
void deallocate (T *obj)
Deallocates an object and destroys it.
void * add_pool (void *mem, size_t bytes)
Adds a new memory pool to the allocator.
void remove_pool (void *pool)
Removes a memory pool from the allocator.
int check_pool (void *pool)
Checks the integrity of a specific memory pool.
void * get_pool (void *pool)
Retrieves the usable memory pointer of a pool.
int check ()
Checks the overall integrity of the allocator.
StorageReport report () const
Generates a storage usage report.
void logStorageReport () const
Logs the storage usage report.
Static Public Member Functions
static void integrity_walker (void *ptr, size_t size, int used, void *user)
Walker function for integrity checks.
Static Public Attributes
static constexpr size_t MAX_POOL = 5
Maximum number of memory pools allowed.
Private Member Functions
void walk_pool (void *pool, Walker walker, void *user)
Walks through the blocks in a pool with a specified walker function.
Private Attributes
Control control
TLSF control structure.
void * memory_pools [MAX_POOL]
Array of memory pool pointers.
size_t pool_sizes [MAX_POOL]
store all pool sizes
size_t pool_count = 0
Number of active pools.
bool initialised = false
Flag indicating if the allocator is initialized.
glock::ILockable * lock_ = nullptr
Detailed Description
A memory allocator class based on the Two-Level Segregated Fit (TLSF) algorithm.
The eAlloc class provides efficient memory management with support for multiple pools, alignment, reallocation, and storage reporting.
Definition at line 32 of file eAlloc.hpp.
Member Typedef Documentation
BlockHeader
using dsa::eAlloc::BlockHeader = tlsf::BlockHeader
TLSF block header type.
Definition at line 55 of file eAlloc.hpp.
Control
using dsa::eAlloc::Control = tlsf::Control
TLSF control structure type.
Definition at line 54 of file eAlloc.hpp.
tlsf
using dsa::eAlloc::tlsf = dsa::TLSF<5>
TLSF allocator with 32 second-level lists.
Definition at line 53 of file eAlloc.hpp.
Walker
using dsa::eAlloc::Walker = tlsf::tlsf_walker
Function type for walking memory blocks.
Definition at line 56 of file eAlloc.hpp.
Constructor & Destructor Documentation
eAlloc()
dsa::eAlloc::eAlloc (void * mem, size_t bytes) [explicit]
Constructs an eAlloc instance with an initial memory pool.
Parameters
mem Pointer to the initial memory block.
bytes Size of the initial memory block in bytes.
Definition at line 12 of file eAlloc.cpp.
{
    tlsf::initialise_control(&control);
    if(!add_pool(mem, bytes))
    {
        LOG::ERROR("E_ALLOC", "Failed to initialize allocator with initial pool (%p, %zu bytes).\n",
                   mem, bytes);
    }
    initialised = true;
}
References add_pool(), control, LOG::ERROR, dsa::TLSF< 5 >::initialise_control(), and initialised.
Member Function Documentation
add_pool()
void * dsa::eAlloc::add_pool (void * mem, size_t bytes)
Adds a new memory pool to the allocator.
Parameters
mem Pointer to the memory block to add as a pool.
bytes Size of the memory block in bytes.
Returns
Pointer to the added pool, or nullptr if addition fails.
Definition at line 23 of file eAlloc.cpp.
{
    if(lock_) glock::LockGuard guard(*lock_);
    if(pool_count >= MAX_POOL)
    {
        LOG::ERROR("E_ALLOC", "Maximum number of pools (%d) reached.\n", MAX_POOL);
        return nullptr;
    }
    size_t pool_overhead = tlsf::pool_overhead();
    size_t align_size = tlsf::align_size();
    size_t min_block_size = tlsf::min_block_size();
    size_t max_block_size = tlsf::max_block_size();
    size_t alloc_overhead = tlsf::alloc_overhead();
    const size_t pool_bytes = tlsf::align_down(bytes - pool_overhead, align_size);
    if((reinterpret_cast<ptrdiff_t>(mem) % align_size) != 0)
    {
        LOG::ERROR("E_ALLOC", "add_pool: Memory must be aligned by %zu bytes", align_size);
        return nullptr;
    }
    if(pool_bytes < min_block_size || pool_bytes > max_block_size)
    {
        LOG::ERROR("E_ALLOC", "add_pool: Memory size must be between %zu and %zu bytes.\n",
                   static_cast<unsigned int>(pool_overhead + min_block_size),
                   static_cast<unsigned int>(pool_overhead + max_block_size));
        return nullptr;
    }
    /*
     ** Create the main free block. Offset the start of the block slightly
     ** so that the prev_phys_block field falls outside of the pool -
     ** it will never be used.
     */
    BlockHeader* block =
        tlsf::offset_to_block_nc(mem, -static_cast<tlsf::tlsfptr_t>(alloc_overhead));
    tlsf::set_size(block, pool_bytes);
    tlsf::set_free(block);
    tlsf::set_prev_used(block);
    tlsf::insert(&control, block);
    /* Split the block to create a zero-size sentinel block. */
    BlockHeader* next = tlsf::link_next(block);
    tlsf::set_size(next, 0);
    tlsf::set_used(next);
    tlsf::set_prev_free(next);
    memory_pools[pool_count] = mem;
    pool_sizes[pool_count] = pool_bytes;
    pool_count++;
    LOG::SUCCESS("E_ALLOC", "Added pool %p (%zu bytes). Total pools: %d\n", mem, bytes, pool_count);
    return mem;
}
References dsa::TLSF< 5 >::align_down(), dsa::TLSF< 5 >::align_size(), dsa::TLSF< 5 >::alloc_overhead(), control, LOG::ERROR, dsa::TLSF< 5 >::insert(), dsa::TLSF< 5 >::link_next(), lock_, dsa::TLSF< 5 >::max_block_size(), MAX_POOL, memory_pools, dsa::TLSF< 5 >::min_block_size(), dsa::TLSF< 5 >::offset_to_block_nc(), pool_count, dsa::TLSF< 5 >::pool_overhead(), pool_sizes, dsa::TLSF< 5 >::set_free(), dsa::TLSF< 5 >::set_prev_free(), dsa::TLSF< 5 >::set_prev_used(), dsa::TLSF< 5 >::set_size(), dsa::TLSF< 5 >::set_used(), and LOG::SUCCESS.
Referenced by eAlloc().
allocate() [1/2]
template<typename T, typename... Args>
T * dsa::eAlloc::allocate (Args &&... args) [inline]
Allocates memory for an object and constructs it with arguments.
Template Parameters
T The type of the object to allocate.
Args Types of the constructor arguments.
Parameters
args Arguments to pass to the object's constructor.
Returns
Pointer to the constructed object, or nullptr if allocation fails.
Definition at line 140 of file eAlloc.hpp.
    {
        void* memory = malloc(sizeof(T));
        if(!memory)
        {
            LOG::ERROR("E_ALLOC", "Memory allocation failed for object.");
            return nullptr;
        }
        try
        {
            return new(memory) T(std::forward<Args>(args)...);
        }
        catch(...)
        {
            free(memory);
            LOG::ERROR("E_ALLOC", "Object construction failed.");
            return nullptr;
        }
    }
References LOG::ERROR, free(), and malloc().
allocate() [2/2]
template<typename T>
T * dsa::eAlloc::allocate (const T & obj) [inline]
Allocates memory for an object and constructs it by copying.
Template Parameters
T The type of the object to allocate.
Parameters
obj The object to copy-construct.
Returns
Pointer to the constructed object, or nullptr if allocation fails.
Definition at line 112 of file eAlloc.hpp.
    {
        void* memory = malloc(sizeof(T));
        if(!memory)
        {
            LOG::ERROR("E_ALLOC", "Memory allocation failed for object.");
            return nullptr;
        }
        try
        {
            return new(memory) T(obj);
        }
        catch(...)
        {
            free(memory);
            LOG::ERROR("E_ALLOC", "Object construction failed.");
            return nullptr;
        }
    }
References LOG::ERROR, free(), and malloc().
calloc()
void * dsa::eAlloc::calloc (size_t num, size_t size)
Allocates memory for an array and initializes it to zero.
Parameters
num Number of elements in the array.
size Size of each element in bytes.
Returns
Pointer to the allocated memory, or nullptr if allocation fails.
Definition at line 275 of file eAlloc.cpp.
{
    if(lock_) glock::LockGuard guard(*lock_);
    size_t total_size;
    if(num > 0 && size > SIZE_MAX / num)
    {
        LOG::ERROR("E_ALLOC", "calloc overflow detected.");
        return nullptr;
    }
    total_size = num * size;
    void* ptr = malloc(total_size);
    if(ptr)
    {
        memset(ptr, 0, total_size);
    }
    return ptr;
}
References LOG::ERROR, lock_, and malloc().
check()
int dsa::eAlloc::check ()
Checks the overall integrity of the allocator.
Returns
Integrity status (0 if intact, non-zero if issues found).
Definition at line 121 of file eAlloc.cpp.
{ return tlsf::check(&control); }
References dsa::TLSF< 5 >::check(), and control.
check_pool()
int dsa::eAlloc::check_pool (void * pool)
Checks the integrity of a specific memory pool.
Parameters
pool Pointer to the pool to check.
Returns
Integrity status (0 if intact, non-zero if issues found).
Definition at line 114 of file eAlloc.cpp.
{
    IntegrityResult integ = {0, 0};
    walk_pool(pool, integrity_walker, &integ);
    return integ.status;
}
References integrity_walker(), dsa::eAlloc::IntegrityResult::status, and walk_pool().
deallocate()
template<typename T>
void dsa::eAlloc::deallocate (T * obj) [inline]
Deallocates an object and destroys it.
Template Parameters
T The type of the object to deallocate.
Parameters
obj Pointer to the object to deallocate.
Definition at line 166 of file eAlloc.hpp.
    {
        if(!obj) return;
        obj->~T();
        free(static_cast<void*>(obj));
    }
References free().
free()
void dsa::eAlloc::free (void * ptr)
Frees a previously allocated memory block.
Parameters
ptr Pointer to the memory block to free.
Definition at line 147 of file eAlloc.cpp.
{
    if(lock_) glock::LockGuard guard(*lock_);
    if(ptr)
    {
        BlockHeader* block = tlsf::from_ptr_nc(ptr);
        if(tlsf::is_free(block))
        {
            LOG::ERROR("E_ALLOC", "Double free detected for block %p! Ignoring.\n", ptr);
            return;
        }
        tlsf::mark_as_free(block);
        block = tlsf::merge_prev(&control, block);
        block = tlsf::merge_next(&control, block);
        tlsf::insert(&control, block);
    }
}
References control, LOG::ERROR, dsa::TLSF< 5 >::from_ptr_nc(), dsa::TLSF< 5 >::insert(), dsa::TLSF< 5 >::is_free(), lock_, dsa::TLSF< 5 >::mark_as_free(), dsa::TLSF< 5 >::merge_next(), and dsa::TLSF< 5 >::merge_prev().
Referenced by allocate(), allocate(), deallocate(), and realloc().
get_pool()
void * dsa::eAlloc::get_pool (void * pool)
Retrieves the usable memory pointer of a pool.
Parameters
pool Pointer to the pool.
Returns
Pointer to the pool's usable memory.
Definition at line 112 of file eAlloc.cpp.
{ return pool; }
integrity_walker()
void dsa::eAlloc::integrity_walker (void * ptr, size_t size, int used, void * user) [static]
Walker function for integrity checks.
Parameters
ptr Pointer to the block.
size Size of the block in bytes.
used Flag indicating if the block is used (non-zero) or free (0).
user User-defined data passed to the walker.
Definition at line 123 of file eAlloc.cpp.
{
    // No locking here! Locking must be handled by the caller, not the walker.
    BlockHeader* block = tlsf::from_ptr_nc(ptr);
    IntegrityResult* integ = static_cast<IntegrityResult*>(user);
    const int this_prev_status = tlsf::is_prev_free(block) ? 1 : 0;
    const int this_status = tlsf::is_free(block) ? 1 : 0;
    const size_t this_block_size = tlsf::get_size(block);
    int status = 0;
    (void)used;
    dsa_insist(integ->prev_status == this_prev_status && "prev status incorrect");
    dsa_insist(size == this_block_size && "block size incorrect");
    integ->prev_status = this_status;
    integ->status += status;
}
References dsa_insist, dsa::TLSF< 5 >::from_ptr_nc(), dsa::TLSF< 5 >::get_size(), dsa::TLSF< 5 >::is_free(), dsa::TLSF< 5 >::is_prev_free(), dsa::eAlloc::IntegrityResult::prev_status, and dsa::eAlloc::IntegrityResult::status.
Referenced by check_pool().
logStorageReport()
void dsa::eAlloc::logStorageReport () const
Logs the storage usage report.
Definition at line 327 of file eAlloc.cpp.
{
    StorageReport sr = report();
    LOG::INFO("E_ALLOC", "=== Storage Report ===");
    LOG::INFO("E_ALLOC", "Total Free Space: %zu bytes", sr.totalFreeSpace);
    LOG::INFO("E_ALLOC", "Largest Free Region: %zu bytes", sr.largestFreeRegion);
    LOG::INFO("E_ALLOC", "Number of Free Blocks: %zu", sr.freeBlockCount);
    LOG::INFO("E_ALLOC", "Fragmentation Factor: %.4f", sr.fragmentationFactor);
}
References dsa::eAlloc::StorageReport::fragmentationFactor, dsa::eAlloc::StorageReport::freeBlockCount, LOG::INFO, dsa::eAlloc::StorageReport::largestFreeRegion, report(), and dsa::eAlloc::StorageReport::totalFreeSpace.
malloc()
void * dsa::eAlloc::malloc (size_t size)
Allocates a block of memory of the specified size.
Parameters
size The size of the memory block to allocate in bytes.
Returns
Pointer to the allocated memory, or nullptr if allocation fails.
Definition at line 139 of file eAlloc.cpp.
{
    if(lock_) glock::LockGuard guard(*lock_);
    const size_t adjust = tlsf::adjust_request_size(size, tlsf::align_size());
    BlockHeader* block = tlsf::locate_free(&control, adjust);
    return tlsf::prepare_used(&control, block, adjust);
}
References dsa::TLSF< 5 >::adjust_request_size(), dsa::TLSF< 5 >::align_size(), control, dsa::TLSF< 5 >::locate_free(), lock_, and dsa::TLSF< 5 >::prepare_used().
Referenced by allocate(), allocate(), calloc(), and realloc().
memalign()
void * dsa::eAlloc::memalign (size_t align, size_t size)
Allocates a memory block with specified alignment and size.
Parameters
align The alignment requirement in bytes (must be a power of 2).
size The size of the memory block to allocate in bytes.
Returns
Pointer to the allocated memory, or nullptr if allocation fails.
Definition at line 177 of file eAlloc.cpp.
{
    if((align & (align - 1)) != 0 || align == 0)
    {
        LOG::ERROR("E_ALLOC", "Alignment must be a non-zero power of two.");
        return nullptr;
    }
    const size_t adjust = tlsf::adjust_request_size(size, tlsf::align_size());
    const size_t gap_minimum = sizeof(BlockHeader);
    const size_t size_with_gap = tlsf::adjust_request_size(adjust + align + gap_minimum, align);
    const size_t aligned_size = (adjust && align > tlsf::align_size()) ? size_with_gap : adjust;
    BlockHeader* block = tlsf::locate_free(&control, aligned_size);
    if(!block) return nullptr;
    dsa_assert(sizeof(BlockHeader) == tlsf::min_block_size() + tlsf::alloc_overhead());
    void* ptr = tlsf::to_ptr_nc(block);
    void* aligned = tlsf::align_ptr(ptr, align);
    uintptr_t aligned_addr = reinterpret_cast<uintptr_t>(aligned);
    uintptr_t block_start = reinterpret_cast<uintptr_t>(ptr);
    size_t gap = aligned_addr - block_start;
    // if (gap && gap < gap_minimum) {
    // const size_t gap_remain = gap_minimum - gap;
    // const size_t offset = dsa_max(gap_remain, align);
    // const void *next_aligned = reinterpret_cast<void *>(
    // reinterpret_cast<tlsf::tlsfptr_t>(aligned) + offset);
    // aligned = tlsf::align_ptr(next_aligned, align);
    // gap = static_cast<size_t>(reinterpret_cast<tlsf::tlsfptr_t>(aligned) -
    // reinterpret_cast<tlsf::tlsfptr_t>(ptr));
    // }
    // if (gap) {
    // dsa_assert(gap >= gap_minimum && "gap size too small");
    // block = tlsf::trim_free_leading(&control, block, gap);
    // }
    // Adjust alignment to ensure sufficient gap
    if(gap < gap_minimum)
    {
        size_t needed = gap_minimum - gap;
        size_t adjust = ((needed + align - 1) / align) * align;
        aligned_addr += adjust;
        aligned = reinterpret_cast<void*>(aligned_addr);
        gap = aligned_addr - block_start;
    }
    if(gap)
    {
        BlockHeader* remaining = tlsf::trim_free_leading(&control, block, gap);
        if(!remaining) return nullptr;
        block = remaining;
    }
    return tlsf::prepare_used(&control, block, adjust);
}
References dsa::TLSF< 5 >::adjust_request_size(), dsa::TLSF< 5 >::align_ptr(), dsa::TLSF< 5 >::align_size(), dsa::TLSF< 5 >::alloc_overhead(), control, dsa_assert, LOG::ERROR, dsa::TLSF< 5 >::locate_free(), dsa::TLSF< 5 >::min_block_size(), dsa::TLSF< 5 >::prepare_used(), dsa::TLSF< 5 >::to_ptr_nc(), and dsa::TLSF< 5 >::trim_free_leading().
realloc()
void * dsa::eAlloc::realloc (void * ptr, size_t size)
Reallocates a memory block to a new size.
Parameters
ptr Pointer to the memory block to reallocate.
size The new size of the memory block in bytes.
Returns
Pointer to the reallocated memory, or nullptr if reallocation fails.
Definition at line 231 of file eAlloc.cpp.
{
    if(lock_) glock::LockGuard guard(*lock_);
    void* p = nullptr;
    if(ptr && size == 0)
    {
        free(ptr);
    }
    else if(!ptr)
    {
        p = malloc(size);
    }
    else
    {
        BlockHeader* block = tlsf::from_ptr_nc(ptr);
        BlockHeader* next = tlsf::next(block);
        const size_t cursize = tlsf::get_size(block);
        const size_t combined = cursize + tlsf::get_size(next) + tlsf::alloc_overhead();
        const size_t adjust = tlsf::adjust_request_size(size, tlsf::align_size());
        dsa_assert(!tlsf::is_free(block) && "block already marked as free");
        if(adjust > cursize && (!tlsf::is_free(next) || adjust > combined))
        {
            p = malloc(size);
            if(p)
            {
                const size_t minsize = dsa_min(cursize, size);
                memcpy(p, ptr, minsize);
                free(ptr);
            }
        }
        else
        {
            if(adjust > cursize)
            {
                tlsf::merge_next(&control, block);
                tlsf::mark_as_used(block);
            }
            tlsf::trim_used(&control, block, adjust);
            p = ptr;
        }
    }
    return p;
}
References dsa::TLSF< 5 >::adjust_request_size(), dsa::TLSF< 5 >::align_size(), dsa::TLSF< 5 >::alloc_overhead(), control, dsa_assert, dsa_min, free(), dsa::TLSF< 5 >::from_ptr_nc(), dsa::TLSF< 5 >::get_size(), dsa::TLSF< 5 >::is_free(), lock_, malloc(), dsa::TLSF< 5 >::mark_as_used(), dsa::TLSF< 5 >::merge_next(), dsa::TLSF< 5 >::next(), and dsa::TLSF< 5 >::trim_used().
remove_pool()
void dsa::eAlloc::remove_pool (void * pool)
Removes a memory pool from the allocator.
Parameters
pool Pointer to the pool to remove.
Note
The pool must contain no allocated blocks; all memory allocated from it must be freed prior to removal, or undefined behavior will result.
Definition at line 79 of file eAlloc.cpp.
{
    if(lock_) glock::LockGuard guard(*lock_);
    for(size_t i = 0; i < pool_count; ++i)
    {
        if(memory_pools[i] == pool)
        {
            BlockHeader* block =
                tlsf::offset_to_block_nc(pool, -static_cast<int>(tlsf::alloc_overhead()));
            BlockHeader* next = tlsf::next(block);
            if(!tlsf::is_free(block) || tlsf::get_size(block) != pool_sizes[i]
               || !tlsf::is_last(next))
            {
                LOG::ERROR("E_ALLOC", "Cannot remove pool %p: it contains allocated blocks.\n",
                           pool);
                return;
            }
            int fl = 0, sl = 0;
            tlsf::mapping_insert(tlsf::get_size(block), &fl, &sl);
            tlsf::remove_free_block(&control, block, fl, sl);
            if(i < pool_count - 1)
            {
                memory_pools[i] = memory_pools[pool_count - 1];
                pool_sizes[i] = pool_sizes[pool_count - 1];
            }
            pool_count--;
            LOG::INFO("E_ALLOC", "Removed pool %p. Remaining pools: %d\n", pool, pool_count);
            return;
        }
    }
    LOG::ERROR("E_ALLOC", "Pool %p not found.\n", pool);
}
References dsa::TLSF< 5 >::alloc_overhead(), control, LOG::ERROR, dsa::TLSF< 5 >::get_size(), LOG::INFO, dsa::TLSF< 5 >::is_free(), dsa::TLSF< 5 >::is_last(), lock_, dsa::TLSF< 5 >::mapping_insert(), memory_pools, dsa::TLSF< 5 >::next(), dsa::TLSF< 5 >::offset_to_block_nc(), pool_count, pool_sizes, and dsa::TLSF< 5 >::remove_free_block().
report()
eAlloc::StorageReport dsa::eAlloc::report () const
Generates a storage usage report.
Returns
StorageReport containing free space and fragmentation details.
Definition at line 293 of file eAlloc.cpp.
{
    if(lock_) glock::LockGuard guard(*lock_);
    StorageReport report{};
    for(size_t fl = 0; fl < tlsf::cabinets(); ++fl)
    {
        if(!(control.fl_bitmap & (1U << fl))) continue;
        for(size_t sl = 0; sl < tlsf::shelves(); ++sl)
        {
            if(!(control.cabinets[fl].sl_bitmap & (1U << sl))) continue;
            BlockHeader* block = control.cabinets[fl].shelves[sl];
            BlockHeader* current = block;
            while(current != &control.block_null)
            {
                size_t size = tlsf::get_size(current);
                report.totalFreeSpace += size;
                if(size > report.largestFreeRegion) report.largestFreeRegion = size;
                report.freeBlockCount++;
                current = current->next_free;
            }
        }
    }
    if(report.totalFreeSpace > 0)
    {
        report.fragmentationFactor =
            1.0 - static_cast<double>(report.largestFreeRegion) / report.totalFreeSpace;
    }
    else
    {
        report.fragmentationFactor = 0.0;
    }
    return report;
}
References dsa::TLSF< 5 >::cabinets(), control, dsa::TLSF< 5 >::get_size(), lock_, report(), and dsa::TLSF< 5 >::shelves().
Referenced by logStorageReport(), and report().
setLock()
void dsa::eAlloc::setLock (glock::ILockable * lock) [inline]
Definition at line 37 of file eAlloc.hpp.
{ lock_ = lock; }
References lock_.
walk_pool()
void dsa::eAlloc::walk_pool (void * pool, Walker walker, void * user) [private]
Walks through the blocks in a pool with a specified walker function.
Parameters
pool Pointer to the pool to walk.
walker Function to apply to each block.
user User-defined data passed to the walker.
Definition at line 165 of file eAlloc.cpp.
{
    if(lock_) glock::LockGuard guard(*lock_);
    Walker pool_walker = walker ? walker : tlsf::default_walker;
    BlockHeader* block = tlsf::offset_to_block_nc(pool, -static_cast<int>(tlsf::alloc_overhead()));
    while(block && !tlsf::is_last(block))
    {
        pool_walker(tlsf::to_ptr_nc(block), tlsf::get_size(block), !tlsf::is_free(block), user);
        block = tlsf::next(block);
    }
}
References dsa::TLSF< 5 >::alloc_overhead(), dsa::TLSF< 5 >::default_walker(), dsa::TLSF< 5 >::get_size(), dsa::TLSF< 5 >::is_free(), dsa::TLSF< 5 >::is_last(), lock_, dsa::TLSF< 5 >::next(), dsa::TLSF< 5 >::offset_to_block_nc(), and dsa::TLSF< 5 >::to_ptr_nc().
Referenced by check_pool().
Member Data Documentation
control
Control dsa::eAlloc::control [private]
TLSF control structure.
Definition at line 231 of file eAlloc.hpp.
Referenced by add_pool(), check(), eAlloc(), free(), malloc(), memalign(), realloc(), remove_pool(), and report().
initialised
bool dsa::eAlloc::initialised = false [private]
Flag indicating if the allocator is initialized.
Definition at line 235 of file eAlloc.hpp.
Referenced by eAlloc().
lock_
glock::ILockable* dsa::eAlloc::lock_ = nullptr [private]
Definition at line 236 of file eAlloc.hpp.
Referenced by add_pool(), calloc(), free(), malloc(), realloc(), remove_pool(), report(), setLock(), and walk_pool().
MAX_POOL
size_t dsa::eAlloc::MAX_POOL = 5 [static], [constexpr]
Maximum number of memory pools allowed.
Definition at line 35 of file eAlloc.hpp.
Referenced by add_pool().
memory_pools
void* dsa::eAlloc::memory_pools[MAX_POOL] [private]
Array of memory pool pointers.
Definition at line 232 of file eAlloc.hpp.
Referenced by add_pool(), and remove_pool().
pool_count
size_t dsa::eAlloc::pool_count = 0 [private]
Number of active pools.
Definition at line 234 of file eAlloc.hpp.
Referenced by add_pool(), and remove_pool().
pool_sizes
size_t dsa::eAlloc::pool_sizes[MAX_POOL] [private]
store all pool sizes
Definition at line 233 of file eAlloc.hpp.
Referenced by add_pool(), and remove_pool().
The documentation for this class was generated from the following files:
src/eAlloc.hpp
src/eAlloc.cpp