dsa::TLSF< SLI > Class Template Reference
#include <tlsf.hpp>
Classes
struct BlockHeader
struct Control
struct SecondLevel
Public Types
typedef ptrdiff_t tlsfptr_t
typedef void(* tlsf_walker) (void *ptr, size_t size, int used, void *user)
Static Public Member Functions
static size_t get_size (const BlockHeader *block)
static void set_size (BlockHeader *block, size_t size)
static bool is_free (const BlockHeader *block)
static bool is_prev_free (const BlockHeader *block)
static bool is_last (const BlockHeader *block)
static void set_free (BlockHeader *block)
static void set_used (BlockHeader *block)
static void set_prev_free (BlockHeader *block)
static void set_prev_used (BlockHeader *block)
static void set_size_and_flags (BlockHeader *block, size_t size, bool free_flag, bool last_flag)
static const void * to_ptr (const BlockHeader *block)
static void * to_ptr_nc (BlockHeader *block)
static const BlockHeader * from_ptr (const void *ptr)
static BlockHeader * from_ptr_nc (void *ptr)
static const BlockHeader * offset_to_block (const void *ptr, size_t size)
static BlockHeader * offset_to_block_nc (void *ptr, size_t size)
static BlockHeader * prev (const BlockHeader *block)
static BlockHeader * next (BlockHeader *block)
static const BlockHeader * next_const (const BlockHeader *block)
static BlockHeader * link_next (BlockHeader *block)
static void mark_as_free (BlockHeader *block)
static void mark_as_used (BlockHeader *block)
static size_t align_up (size_t x, size_t align)
static size_t align_down (size_t x, size_t align)
static void * align_ptr (const void *ptr, size_t align)
static size_t adjust_request_size (size_t size, size_t align)
static void mapping_insert (size_t size, int *fli, int *sli)
static void mapping_search (size_t size, int *fli, int *sli)
static BlockHeader * search_suitable_block (Control *control, int *fli, int *sli)
static void remove_free_block (Control *control, BlockHeader *block, int fl, int sl)
static void insert_free_block (Control *control, BlockHeader *block, int fl, int sl)
static void remove (Control *control, BlockHeader *block)
static void insert (Control *control, BlockHeader *block)
static bool can_split (BlockHeader *block, size_t size)
static BlockHeader * split (BlockHeader *block, size_t size)
static BlockHeader * absorb (BlockHeader *prev, BlockHeader *block)
static BlockHeader * merge_prev (Control *control, BlockHeader *block)
static BlockHeader * merge_next (Control *control, BlockHeader *block)
static void trim_free (Control *control, BlockHeader *block, size_t size)
static void trim_used (Control *control, BlockHeader *block, size_t size)
static BlockHeader * trim_free_leading (Control *control, BlockHeader *block, size_t size)
static BlockHeader * locate_free (Control *control, size_t size)
static void * prepare_used (Control *control, BlockHeader *block, size_t size)
static void initialise_control (Control *control)
static void default_walker (void *ptr, size_t size, int used, void *user)
static int check (Control *control)
static constexpr size_t cabinets ()
static constexpr size_t shelves ()
static constexpr size_t total_shelves ()
static constexpr size_t size ()
static constexpr size_t align_size ()
static constexpr size_t min_block_size ()
static constexpr size_t max_block_size ()
static constexpr size_t pool_overhead ()
static constexpr size_t alloc_overhead ()
static size_t block_size (void *ptr)
Private Types
typedef char static_assert__LINE__[(sizeof(unsigned int) *CHAR_BIT >=SLI_COUNT) ? 1 :-1]
typedef char static_assert__LINE__[(BLOCK_ALIGNMENT==SMALL_BLOCK_SIZE/SLI_COUNT) ? 1 :-1]
Static Private Attributes
static constexpr size_t SL_INDEX_LOG2 = SLI
static constexpr size_t ALIGN_SIZE_LOG2 = 2
static constexpr size_t BLOCK_ALIGNMENT = (1 << ALIGN_SIZE_LOG2)
static constexpr size_t FL_INDEX_MAX = 31
static constexpr size_t SLI_COUNT = (1 << SL_INDEX_LOG2)
static constexpr size_t FL_INDEX_SHIFT = (SL_INDEX_LOG2 + ALIGN_SIZE_LOG2)
static constexpr size_t FL_INDEX_COUNT = (FL_INDEX_MAX - FL_INDEX_SHIFT + 1)
static constexpr size_t SMALL_BLOCK_SIZE = (1 << FL_INDEX_SHIFT)
static constexpr size_t ALIGN_SIZE = BLOCK_ALIGNMENT
static constexpr size_t free_bit = 1 << 0
static constexpr size_t prev_free_bit = 1 << 1
static constexpr size_t flag_mask = prev_free_bit | free_bit
static constexpr size_t block_header_overhead = sizeof(size_t)
static constexpr size_t block_start_offset
static constexpr size_t block_size_min = sizeof(BlockHeader) - sizeof(BlockHeader*)
static constexpr size_t block_size_max = static_cast<size_t>(1 << FL_INDEX_MAX)
Detailed Description
template<size_t SLI = 5>
class dsa::TLSF< SLI >
Definition at line 37 of file tlsf.hpp.
Member Typedef Documentation
static_assert__LINE__ [1/2]
template<size_t SLI = 5>
typedef char dsa::TLSF< SLI >::static_assert__LINE__[(BLOCK_ALIGNMENT==SMALL_BLOCK_SIZE/SLI_COUNT) ? 1 :-1] [private]
Definition at line 78 of file tlsf.hpp.
static_assert__LINE__ [2/2]
template<size_t SLI = 5>
typedef char dsa::TLSF< SLI >::static_assert__LINE__[(sizeof(unsigned int) *CHAR_BIT >=SLI_COUNT) ? 1 :-1] [private]
Definition at line 77 of file tlsf.hpp.
tlsf_walker
template<size_t SLI = 5>
typedef void(* dsa::TLSF< SLI >::tlsf_walker) (void *ptr, size_t size, int used, void *user)
Definition at line 96 of file tlsf.hpp.
tlsfptr_t
template<size_t SLI = 5>
typedef ptrdiff_t dsa::TLSF< SLI >::tlsfptr_t
Definition at line 95 of file tlsf.hpp.
Member Function Documentation
absorb()
template<size_t SLI = 5>
static BlockHeader * dsa::TLSF< SLI >::absorb (BlockHeader * prev, BlockHeader * block) [inline], [static]
Definition at line 363 of file tlsf.hpp.
    {
        dsa_assert(!is_last(prev));
        set_size(prev, get_size(prev) + get_size(block) + block_header_overhead);
        link_next(prev);
        return prev;
    }
Referenced by dsa::TLSF< 5 >::merge_next(), and dsa::TLSF< 5 >::merge_prev().
adjust_request_size()
template<size_t SLI = 5>
static size_t dsa::TLSF< SLI >::adjust_request_size (size_t size, size_t align) [inline], [static]
Definition at line 233 of file tlsf.hpp.
    {
        size_t adjust = 0;
        if(size)
        {
            const size_t aligned = align_up(size, align);
            if(aligned < block_size_max) adjust = dsa_max(aligned, block_size_min);
        }
        return adjust;
    }
align_down()
template<size_t SLI = 5>
static size_t dsa::TLSF< SLI >::align_down (size_t x, size_t align) [inline], [static]
Definition at line 217 of file tlsf.hpp.
    {
        dsa_assert(0 == (align & (align - 1)) && "must align to a power of two");
        return x - (x & (align - 1));
    }
align_ptr()
template<size_t SLI = 5>
static void * dsa::TLSF< SLI >::align_ptr (const void * ptr, size_t align) [inline], [static]
Definition at line 223 of file tlsf.hpp.
    {
        const tlsfptr_t aligned = (reinterpret_cast<tlsfptr_t>(ptr) + (align - 1)) & ~(align - 1);
        dsa_assert(0 == (align & (align - 1)) && "must align to a power of two");
        return reinterpret_cast<void*>(aligned);
    }
Referenced by dsa::TLSF< 5 >::insert_free_block(), and dsa::TLSF< 5 >::split().
align_size()
template<size_t SLI = 5>
static constexpr size_t dsa::TLSF< SLI >::align_size () [inline], [static], [constexpr]
Definition at line 536 of file tlsf.hpp.
{ return BLOCK_ALIGNMENT; }
align_up()
template<size_t SLI = 5>
static size_t dsa::TLSF< SLI >::align_up (size_t x, size_t align) [inline], [static]
Definition at line 211 of file tlsf.hpp.
    {
        dsa_assert(0 == (align & (align - 1)) && "must align to a power of two");
        return (x + (align - 1)) & ~(align - 1);
    }
Referenced by dsa::TLSF< 5 >::adjust_request_size().
alloc_overhead()
template<size_t SLI = 5>
static constexpr size_t dsa::TLSF< SLI >::alloc_overhead () [inline], [static], [constexpr]
Definition at line 540 of file tlsf.hpp.
{ return block_header_overhead; }
block_size()
template<size_t SLI = 5>
static size_t dsa::TLSF< SLI >::block_size (void * ptr) [inline], [static]
Definition at line 541 of file tlsf.hpp.
    {
        size_t size = 0;
        if(ptr)
        {
            const BlockHeader* block = from_ptr_nc(ptr);
            size = get_size(block);
        }
        return size;
    }
cabinets()
template<size_t SLI = 5>
static constexpr size_t dsa::TLSF< SLI >::cabinets () [inline], [static], [constexpr]
Definition at line 532 of file tlsf.hpp.
{ return FL_INDEX_COUNT; }
Referenced by dsa::TLSF< 5 >::check().
can_split()
template<size_t SLI = 5>
static bool dsa::TLSF< SLI >::can_split (BlockHeader * block, size_t size) [inline], [static]
Definition at line 347 of file tlsf.hpp.
    {
        return get_size(block) >= sizeof(BlockHeader) + size;
    }
Referenced by dsa::TLSF< 5 >::trim_free(), dsa::TLSF< 5 >::trim_free_leading(), and dsa::TLSF< 5 >::trim_used().
check()
template<size_t SLI = 5>
static int dsa::TLSF< SLI >::check (Control * control) [inline], [static]
Definition at line 480 of file tlsf.hpp.
    {
        int i, j;
        int status = 0;
        /* Check that the free lists and bitmaps are accurate. */
        for(i = 0; i < cabinets(); ++i)
        {
            for(j = 0; j < shelves(); ++j)
            {
                const int fl_map = control->fl_bitmap & (1U << i);
                const int sl_list = control->cabinets[i].sl_bitmap;
                const int sl_map = sl_list & (1U << j);
                const BlockHeader* block = control->cabinets[i].shelves[j];
                /* Check that first- and second-level lists agree. */
                if(!fl_map)
                {
                    dsa_insist(!sl_map && "second-level map must be null");
                }
                if(!sl_map)
                {
                    dsa_insist(block == &control->block_null && "block list must be null");
                    continue;
                }
                /* Check that there is at least one free block. */
                dsa_insist(sl_list && "no free blocks in second-level map");
                dsa_insist(block != &control->block_null && "block should not be null");
                while(block != &control->block_null)
                {
                    int fli, sli;
                    dsa_insist(is_free(block) && "block should be free");
                    dsa_insist(!is_prev_free(block) && "blocks should have coalesced");
                    dsa_insist(!is_free(next_const(block)) && "blocks should have coalesced");
                    dsa_insist(is_prev_free(next_const(block)) && "block should be free");
                    dsa_insist(get_size(block) >= min_block_size() && "block not minimum size");
                    mapping_insert(get_size(block), &fli, &sli);
                    dsa_insist(fli == i && sli == j && "block size indexed in wrong list");
                    block = block->next_free;
                }
            }
        }
        return status;
    }
default_walker()
template<size_t SLI = 5>
static void dsa::TLSF< SLI >::default_walker (void * ptr, size_t size, int used, void * user) [inline], [static]
Definition at line 473 of file tlsf.hpp.
    {
        (void)user;
        LOG::INFO("\t%p %s size: %x (%p)\n", ptr, used ? "used" : "free", (unsigned int)size,
                  from_ptr_nc(ptr));
    }
from_ptr()
template<size_t SLI = 5>
static const BlockHeader * dsa::TLSF< SLI >::from_ptr (const void * ptr) [inline], [static]
Definition at line 146 of file tlsf.hpp.
    {
        return reinterpret_cast<const BlockHeader*>(reinterpret_cast<const unsigned char*>(ptr)
                                                    - block_start_offset);
    }
from_ptr_nc()
template<size_t SLI = 5>
static BlockHeader * dsa::TLSF< SLI >::from_ptr_nc (void * ptr) [inline], [static]
Definition at line 151 of file tlsf.hpp.
    {
        return reinterpret_cast<BlockHeader*>(reinterpret_cast<unsigned char*>(ptr)
                                              - block_start_offset);
    }
Referenced by dsa::TLSF< 5 >::block_size(), and dsa::TLSF< 5 >::default_walker().
get_size()
template<size_t SLI = 5>
static size_t dsa::TLSF< SLI >::get_size (const BlockHeader * block) [inline], [static]
Definition at line 98 of file tlsf.hpp.
    {
        return block->size_and_flags & ~flag_mask;
    }
Referenced by dsa::TLSF< 5 >::absorb(), dsa::TLSF< 5 >::block_size(), dsa::TLSF< 5 >::can_split(), dsa::TLSF< 5 >::check(), dsa::TLSF< 5 >::insert(), dsa::TLSF< 5 >::is_last(), dsa::TLSF< 5 >::locate_free(), dsa::TLSF< 5 >::next(), dsa::TLSF< 5 >::next_const(), dsa::TLSF< 5 >::remove(), and dsa::TLSF< 5 >::split().
initialise_control()
template<size_t SLI = 5>
static void dsa::TLSF< SLI >::initialise_control (Control * control) [inline], [static]
Definition at line 456 of file tlsf.hpp.
    {
        int i, j;
        control->block_null.next_free = &control->block_null;
        control->block_null.prev_free = &control->block_null;
        control->fl_bitmap = 0;
        for(i = 0; i < FL_INDEX_COUNT; ++i)
        {
            control->cabinets[i].sl_bitmap = 0;
            for(j = 0; j < SLI_COUNT; ++j)
            {
                control->cabinets[i].shelves[j] = &control->block_null;
            }
        }
    }
insert()
template<size_t SLI = 5>
static void dsa::TLSF< SLI >::insert (Control * control, BlockHeader * block) [inline], [static]
Definition at line 341 of file tlsf.hpp.
    {
        int fl, sl;
        mapping_insert(get_size(block), &fl, &sl);
        insert_free_block(control, block, fl, sl);
    }
Referenced by dsa::TLSF< 5 >::trim_free(), dsa::TLSF< 5 >::trim_free_leading(), and dsa::TLSF< 5 >::trim_used().
insert_free_block()
template<size_t SLI = 5>
static void dsa::TLSF< SLI >::insert_free_block (Control * control, BlockHeader * block, int fl, int sl) [inline], [static]
Definition at line 317 of file tlsf.hpp.
    {
        BlockHeader* current = control->cabinets[fl].shelves[sl];
        dsa_assert(current && "free list cannot have a null entry");
        dsa_assert(block && "cannot insert a null entry into the free list");
        block->next_free = current;
        block->prev_free = &control->block_null;
        if(current) current->prev_free = block;
        dsa_assert(to_ptr(block) == align_ptr(to_ptr(block), ALIGN_SIZE)
                   && "block not aligned properly");
        control->cabinets[fl].shelves[sl] = block;
        control->fl_bitmap |= (1U << fl);
        control->cabinets[fl].sl_bitmap |= (1U << sl);
    }
Referenced by dsa::TLSF< 5 >::insert().
is_free()
template<size_t SLI = 5>
static bool dsa::TLSF< SLI >::is_free (const BlockHeader * block) [inline], [static]
Definition at line 108 of file tlsf.hpp.
    {
        return block->size_and_flags & free_bit;
    }
Referenced by dsa::TLSF< 5 >::check(), dsa::TLSF< 5 >::merge_next(), dsa::TLSF< 5 >::merge_prev(), dsa::TLSF< 5 >::trim_free(), and dsa::TLSF< 5 >::trim_used().
is_last()
template<size_t SLI = 5>
static bool dsa::TLSF< SLI >::is_last (const BlockHeader * block) [inline], [static]
Definition at line 117 of file tlsf.hpp.
{ return get_size(block) == 0; }
Referenced by dsa::TLSF< 5 >::absorb(), dsa::TLSF< 5 >::merge_next(), dsa::TLSF< 5 >::next(), and dsa::TLSF< 5 >::next_const().
is_prev_free()
template<size_t SLI = 5>
static bool dsa::TLSF< SLI >::is_prev_free (const BlockHeader * block) [inline], [static]
Definition at line 112 of file tlsf.hpp.
    {
        return block->size_and_flags & prev_free_bit;
    }
Referenced by dsa::TLSF< 5 >::check(), dsa::TLSF< 5 >::merge_prev(), and dsa::TLSF< 5 >::prev().
link_next()
template<size_t SLI = 5>
static BlockHeader * dsa::TLSF< SLI >::link_next (BlockHeader * block) [inline], [static]
Definition at line 191 of file tlsf.hpp.
    {
        BlockHeader* n = next(block);
        n->prev_phys_block = block;
        return n;
    }
Referenced by dsa::TLSF< 5 >::absorb(), dsa::TLSF< 5 >::mark_as_free(), dsa::TLSF< 5 >::trim_free(), and dsa::TLSF< 5 >::trim_free_leading().
locate_free()
template<size_t SLI = 5>
static BlockHeader * dsa::TLSF< SLI >::locate_free (Control * control, size_t size) [inline], [static]
Definition at line 428 of file tlsf.hpp.
    {
        int fl = 0, sl = 0;
        BlockHeader* block = 0;
        if(size)
        {
            mapping_search(size, &fl, &sl);
            if(fl < FL_INDEX_COUNT) block = search_suitable_block(control, &fl, &sl);
        }
        if(block)
        {
            dsa_assert(get_size(block) >= size);
            remove_free_block(control, block, fl, sl);
        }
        return block;
    }
mapping_insert()
template<size_t SLI = 5>
static void dsa::TLSF< SLI >::mapping_insert (size_t size, int * fli, int * sli) [inline], [static]
Definition at line 248 of file tlsf.hpp.
    {
        int fl, sl;
        if(size < SMALL_BLOCK_SIZE)
        {
            fl = 0;
            sl = static_cast<int>(size) / (SMALL_BLOCK_SIZE / SLI_COUNT);
        }
        else
        {
            fl = fls(size);
            sl = (static_cast<int>(size >> (fl - SL_INDEX_LOG2)) ^ (1 << SL_INDEX_LOG2));
            fl -= (FL_INDEX_SHIFT - 1);
        }
        *fli = fl;
        *sli = sl;
    }
Referenced by dsa::TLSF< 5 >::check(), dsa::TLSF< 5 >::insert(), dsa::TLSF< 5 >::mapping_search(), and dsa::TLSF< 5 >::remove().
mapping_search()
template<size_t SLI = 5>
static void dsa::TLSF< SLI >::mapping_search (size_t size, int * fli, int * sli) [inline], [static]
Definition at line 267 of file tlsf.hpp.
    {
        if(size >= SMALL_BLOCK_SIZE)
        {
            const size_t round = (1 << (fls(size) - SL_INDEX_LOG2)) - 1;
            size += round;
        }
        mapping_insert(size, fli, sli);
    }
Referenced by dsa::TLSF< 5 >::locate_free().
mark_as_free()
template<size_t SLI = 5>
static void dsa::TLSF< SLI >::mark_as_free (BlockHeader * block) [inline], [static]
Definition at line 197 of file tlsf.hpp.
    {
        /* Link the block to the next block, first. */
        BlockHeader* next = link_next(block);
        set_prev_free(next);
        set_free(block);
    }
Referenced by dsa::TLSF< 5 >::split().
mark_as_used()
template<size_t SLI = 5>
static void dsa::TLSF< SLI >::mark_as_used (BlockHeader * block) [inline], [static]
Definition at line 205 of file tlsf.hpp.
    {
        BlockHeader* n = next(block);
        set_prev_used(n);
        set_used(block);
    }
Referenced by dsa::TLSF< 5 >::prepare_used().
max_block_size()
template<size_t SLI = 5>
static constexpr size_t dsa::TLSF< SLI >::max_block_size () [inline], [static], [constexpr]
Definition at line 538 of file tlsf.hpp.
{ return block_size_max; }
merge_next()
template<size_t SLI = 5>
static BlockHeader * dsa::TLSF< SLI >::merge_next (Control * control, BlockHeader * block) [inline], [static]
Definition at line 382 of file tlsf.hpp.
    {
        BlockHeader* n = next(block);
        dsa_assert(n && "next physical block can't be null");
        if(is_free(n))
        {
            dsa_assert(!is_last(block) && "previous block can't be last");
            remove(control, n);
            block = absorb(block, n);
        }
        return block;
    }
Referenced by dsa::TLSF< 5 >::trim_used().
merge_prev()
template<size_t SLI = 5>
static BlockHeader * dsa::TLSF< SLI >::merge_prev (Control * control, BlockHeader * block) [inline], [static]
Definition at line 370 of file tlsf.hpp.
    {
        if(is_prev_free(block))
        {
            BlockHeader* p = prev(block);
            dsa_assert(p && "prev physical block can't be null");
            dsa_assert(is_free(p) && "prev block is not free though marked as such");
            remove(control, p);
            block = absorb(p, block);
        }
        return block;
    }
min_block_size()
template<size_t SLI = 5>
static constexpr size_t dsa::TLSF< SLI >::min_block_size () [inline], [static], [constexpr]
Definition at line 537 of file tlsf.hpp.
{ return block_size_min; }
Referenced by dsa::TLSF< 5 >::check().
next()
template<size_t SLI = 5>
static BlockHeader * dsa::TLSF< SLI >::next (BlockHeader * block) [inline], [static]
Definition at line 175 of file tlsf.hpp.
    {
        BlockHeader* n =
            offset_to_block_nc(to_ptr_nc(block), get_size(block) - block_header_overhead);
        dsa_assert(!is_last(block));
        return n;
    }
Referenced by dsa::TLSF< 5 >::link_next(), dsa::TLSF< 5 >::mark_as_used(), and dsa::TLSF< 5 >::merge_next().
next_const()
template<size_t SLI = 5>
static const BlockHeader * dsa::TLSF< SLI >::next_const (const BlockHeader * block) [inline], [static]
Definition at line 182 of file tlsf.hpp.
    {
        const BlockHeader* n =
            offset_to_block(to_ptr(block), get_size(block) - block_header_overhead);
        dsa_assert(!is_last(block));
        return n;
    }
Referenced by dsa::TLSF< 5 >::check().
offset_to_block()
template<size_t SLI = 5>
static const BlockHeader * dsa::TLSF< SLI >::offset_to_block (const void * ptr, size_t size) [inline], [static]
Definition at line 158 of file tlsf.hpp.
    {
        return reinterpret_cast<const BlockHeader*>(reinterpret_cast<const char*>(ptr) + size);
    }
Referenced by dsa::TLSF< 5 >::next_const().
offset_to_block_nc()
template<size_t SLI = 5>
static BlockHeader * dsa::TLSF< SLI >::offset_to_block_nc (void * ptr, size_t size) [inline], [static]
Definition at line 162 of file tlsf.hpp.
    {
        return reinterpret_cast<BlockHeader*>(reinterpret_cast<char*>(ptr) + size);
    }
Referenced by dsa::TLSF< 5 >::next(), and dsa::TLSF< 5 >::split().
pool_overhead()
template<size_t SLI = 5>
static constexpr size_t dsa::TLSF< SLI >::pool_overhead () [inline], [static], [constexpr]
Definition at line 539 of file tlsf.hpp.
{ return 2 * block_header_overhead; }
prepare_used()
template<size_t SLI = 5>
static void * dsa::TLSF< SLI >::prepare_used (Control * control, BlockHeader * block, size_t size) [inline], [static]
Definition at line 444 of file tlsf.hpp.
    {
        void* p = nullptr;
        if(block)
        {
            dsa_assert(size && "size must be non-zero");
            trim_free(control, block, size);
            mark_as_used(block);
            p = to_ptr_nc(block);
        }
        return p;
    }
prev()
template<size_t SLI = 5>
static BlockHeader * dsa::TLSF< SLI >::prev (const BlockHeader * block) [inline], [static]
Definition at line 168 of file tlsf.hpp.
    {
        dsa_assert(is_prev_free(block) && "previous block must be free");
        return block->prev_phys_block;
    }
Referenced by dsa::TLSF< 5 >::merge_prev().
remove()
template<size_t SLI = 5>
static void dsa::TLSF< SLI >::remove (Control * control, BlockHeader * block) [inline], [static]
Definition at line 333 of file tlsf.hpp.
    {
        int fl, sl;
        mapping_insert(get_size(block), &fl, &sl);
        remove_free_block(control, block, fl, sl);
    }
Referenced by dsa::TLSF< 5 >::merge_next(), and dsa::TLSF< 5 >::merge_prev().
remove_free_block()
template<size_t SLI = 5>
static void dsa::TLSF< SLI >::remove_free_block (Control * control, BlockHeader * block, int fl, int sl) [inline], [static]
Definition at line 298 of file tlsf.hpp.
    {
        BlockHeader* prev = block->prev_free;
        BlockHeader* next = block->next_free;
        if(next) next->prev_free = prev;
        if(prev) prev->next_free = next;
        if(control->cabinets[fl].shelves[sl] == block)
        {
            control->cabinets[fl].shelves[sl] = next;
            if(next == &control->block_null)
            {
                control->cabinets[fl].sl_bitmap &= ~(1U << sl);
                if(!control->cabinets[fl].sl_bitmap)
                {
                    control->fl_bitmap &= ~(1U << fl);
                }
            }
        }
    }
Referenced by dsa::TLSF< 5 >::locate_free(), and dsa::TLSF< 5 >::remove().
search_suitable_block()
template<size_t SLI = 5>
static BlockHeader * dsa::TLSF< SLI >::search_suitable_block (Control * control, int * fli, int * sli) [inline], [static]
Definition at line 276 of file tlsf.hpp.
    {
        int fl = *fli;
        int sl = *sli;
        unsigned int sl_map = control->cabinets[fl].sl_bitmap & (~0U << sl);
        if(!sl_map)
        {
            /* No block exists. Search in the next largest first-level list. */
            const unsigned int fl_map = control->fl_bitmap & (~0U << (fl + 1));
            if(!fl_map) return nullptr;
            fl = ffs(fl_map);
            *fli = fl;
            sl_map = control->cabinets[fl].sl_bitmap;
        }
        dsa_assert(sl_map && "internal error - second level bitmap is null");
        sl = ffs(sl_map);
        *sli = sl;
        /* Return the first block in the free list. */
        return control->cabinets[fl].shelves[sl];
    }
Referenced by dsa::TLSF< 5 >::locate_free().
set_free()
template<size_t SLI = 5>
static void dsa::TLSF< SLI >::set_free (BlockHeader * block) [inline], [static]
Definition at line 119 of file tlsf.hpp.
{ block->size_and_flags |= free_bit; }
Referenced by dsa::TLSF< 5 >::mark_as_free().
set_prev_free()
template<size_t SLI = 5>
static void dsa::TLSF< SLI >::set_prev_free (BlockHeader * block) [inline], [static]
Definition at line 123 of file tlsf.hpp.
{ block->size_and_flags |= prev_free_bit; }
Referenced by dsa::TLSF< 5 >::mark_as_free(), dsa::TLSF< 5 >::trim_free(), and dsa::TLSF< 5 >::trim_free_leading().
set_prev_used()
template<size_t SLI = 5>
static void dsa::TLSF< SLI >::set_prev_used (BlockHeader * block) [inline], [static]
Definition at line 124 of file tlsf.hpp.
    {
        block->size_and_flags &= ~prev_free_bit;
    }
Referenced by dsa::TLSF< 5 >::mark_as_used(), and dsa::TLSF< 5 >::trim_used().
set_size()
template<size_t SLI = 5>
static void dsa::TLSF< SLI >::set_size (BlockHeader * block, size_t size) [inline], [static]
Definition at line 103 of file tlsf.hpp.
    {
        block->size_and_flags = (size & ~flag_mask) | (block->size_and_flags & flag_mask);
    }
Referenced by dsa::TLSF< 5 >::absorb(), and dsa::TLSF< 5 >::split().
set_size_and_flags()
template<size_t SLI = 5>
static void dsa::TLSF< SLI >::set_size_and_flags (BlockHeader * block, size_t size, bool free_flag, bool last_flag) [inline], [static]
Definition at line 129 of file tlsf.hpp.
    {
        size_t flags = (free_flag ? free_bit : 0) | (last_flag ? prev_free_bit : 0);
        block->size_and_flags = (size & ~flag_mask) | flags;
    }
set_used()
template<size_t SLI = 5>
static void dsa::TLSF< SLI >::set_used (BlockHeader * block) [inline], [static]
Definition at line 121 of file tlsf.hpp.
{ block->size_and_flags &= ~free_bit; }
Referenced by dsa::TLSF< 5 >::mark_as_used().
shelves()
template<size_t SLI = 5>
static constexpr size_t dsa::TLSF< SLI >::shelves () [inline], [static], [constexpr]
Definition at line 533 of file tlsf.hpp.
{ return SLI_COUNT; }
Referenced by dsa::TLSF< 5 >::check().
size()
template<size_t SLI = 5>
static constexpr size_t dsa::TLSF< SLI >::size () [inline], [static], [constexpr]
Definition at line 535 of file tlsf.hpp.
{ return sizeof(Control); }
split()
template<size_t SLI = 5>
static BlockHeader * dsa::TLSF< SLI >::split (BlockHeader * block, size_t size) [inline], [static]
Definition at line 351 of file tlsf.hpp.
    {
        BlockHeader* remaining = offset_to_block_nc(to_ptr_nc(block), size - block_header_overhead);
        const size_t remain_size = get_size(block) - (size + block_header_overhead);
        dsa_assert(to_ptr(remaining) == align_ptr(to_ptr(remaining), BLOCK_ALIGNMENT)
                   && "remaining block not aligned properly");
        set_size(remaining, remain_size);
        dsa_assert(get_size(remaining) >= block_size_min && "block split with invalid size");
        set_size(block, size);
        mark_as_free(remaining);
        return remaining;
    }
Referenced by dsa::TLSF< 5 >::trim_free(), dsa::TLSF< 5 >::trim_free_leading(), and dsa::TLSF< 5 >::trim_used().
to_ptr()
template<size_t SLI = 5>
static const void * dsa::TLSF< SLI >::to_ptr (const BlockHeader * block) [inline], [static]
Definition at line 136 of file tlsf.hpp.
    {
        return reinterpret_cast<const void*>(reinterpret_cast<const unsigned char*>(block)
                                             + block_start_offset);
    }
Referenced by dsa::TLSF< 5 >::insert_free_block(), dsa::TLSF< 5 >::next_const(), and dsa::TLSF< 5 >::split().
to_ptr_nc()
template<size_t SLI = 5>
static void * dsa::TLSF< SLI >::to_ptr_nc (BlockHeader * block) [inline], [static]
Definition at line 141 of file tlsf.hpp.
    {
        return reinterpret_cast<void*>(reinterpret_cast<unsigned char*>(block)
                                       + block_start_offset);
    }
Referenced by dsa::TLSF< 5 >::next(), dsa::TLSF< 5 >::prepare_used(), and dsa::TLSF< 5 >::split().
total_shelves()
template<size_t SLI = 5>
static constexpr size_t dsa::TLSF< SLI >::total_shelves () [inline], [static], [constexpr]
Definition at line 534 of file tlsf.hpp.
{ return SLI_COUNT * FL_INDEX_COUNT; }
trim_free()
template<size_t SLI = 5>
static void dsa::TLSF< SLI >::trim_free (Control * control, BlockHeader * block, size_t size) [inline], [static]
Definition at line 394 of file tlsf.hpp.
    {
        dsa_assert(is_free(block) && "block must be free");
        if(can_split(block, size))
        {
            BlockHeader* remaining_block = split(block, size);
            link_next(block);
            set_prev_free(remaining_block);
            insert(control, remaining_block);
        }
    }
Referenced by dsa::TLSF< 5 >::prepare_used().
trim_free_leading()
template<size_t SLI = 5>
static BlockHeader * dsa::TLSF< SLI >::trim_free_leading (Control * control, BlockHeader * block, size_t size) [inline], [static]
Definition at line 416 of file tlsf.hpp.
    {
        BlockHeader* remaining_block = block;
        if(can_split(block, size))
        {
            remaining_block = split(block, size - block_header_overhead);
            set_prev_free(remaining_block);
            link_next(block);
            insert(control, block);
        }
        return remaining_block;
    }
trim_used()
template<size_t SLI = 5>
static void dsa::TLSF< SLI >::trim_used (Control * control, BlockHeader * block, size_t size) [inline], [static]
Definition at line 405 of file tlsf.hpp.
    {
        dsa_assert(!is_free(block) && "block must be free");
        if(can_split(block, size))
        {
            BlockHeader* remaining_block = split(block, size);
            set_prev_used(remaining_block);
            remaining_block = merge_next(control, remaining_block);
            insert(control, remaining_block);
        }
    }
Member Data Documentation
ALIGN_SIZE
template<size_t SLI = 5>
size_t dsa::TLSF< SLI >::ALIGN_SIZE = BLOCK_ALIGNMENT [static], [constexpr], [private]
Definition at line 60 of file tlsf.hpp.
ALIGN_SIZE_LOG2
template<size_t SLI = 5>
size_t dsa::TLSF< SLI >::ALIGN_SIZE_LOG2 = 2 [static], [constexpr], [private]
Definition at line 53 of file tlsf.hpp.
BLOCK_ALIGNMENT
template<size_t SLI = 5>
size_t dsa::TLSF< SLI >::BLOCK_ALIGNMENT = (1 << ALIGN_SIZE_LOG2) [static], [constexpr], [private]
Definition at line 54 of file tlsf.hpp.
block_header_overhead
template<size_t SLI = 5>
size_t dsa::TLSF< SLI >::block_header_overhead = sizeof(size_t) [static], [constexpr], [private]
Definition at line 71 of file tlsf.hpp.
block_size_max
template<size_t SLI = 5>
size_t dsa::TLSF< SLI >::block_size_max = static_cast<size_t>(1 << FL_INDEX_MAX) [static], [constexpr], [private]
Definition at line 75 of file tlsf.hpp.
block_size_min
template<size_t SLI = 5>
size_t dsa::TLSF< SLI >::block_size_min = sizeof(BlockHeader) - sizeof(BlockHeader*) [static], [constexpr], [private]
Definition at line 74 of file tlsf.hpp.
block_start_offset
template<size_t SLI = 5>
size_t dsa::TLSF< SLI >::block_start_offset [static], [constexpr], [private]
Initial value:
=
        offsetof(BlockHeader, size_and_flags) + block_header_overhead
Definition at line 72 of file tlsf.hpp.
FL_INDEX_COUNT
template<size_t SLI = 5>
size_t dsa::TLSF< SLI >::FL_INDEX_COUNT = (FL_INDEX_MAX - FL_INDEX_SHIFT + 1) [static], [constexpr], [private]
Definition at line 58 of file tlsf.hpp.
FL_INDEX_MAX
template<size_t SLI = 5>
size_t dsa::TLSF< SLI >::FL_INDEX_MAX = 31 [static], [constexpr], [private]
Definition at line 55 of file tlsf.hpp.
FL_INDEX_SHIFT
template<size_t SLI = 5>
size_t dsa::TLSF< SLI >::FL_INDEX_SHIFT = (SL_INDEX_LOG2 + ALIGN_SIZE_LOG2) [static], [constexpr], [private]
Definition at line 57 of file tlsf.hpp.
flag_mask
template<size_t SLI = 5>
size_t dsa::TLSF< SLI >::flag_mask = prev_free_bit | free_bit [static], [constexpr], [private]
Definition at line 69 of file tlsf.hpp.
free_bit
template<size_t SLI = 5>
size_t dsa::TLSF< SLI >::free_bit = 1 << 0 [static], [constexpr], [private]
Definition at line 67 of file tlsf.hpp.
prev_free_bit
template<size_t SLI = 5>
size_t dsa::TLSF< SLI >::prev_free_bit = 1 << 1 [static], [constexpr], [private]
Definition at line 68 of file tlsf.hpp.
SL_INDEX_LOG2
template<size_t SLI = 5>
size_t dsa::TLSF< SLI >::SL_INDEX_LOG2 = SLI [static], [constexpr], [private]
Definition at line 52 of file tlsf.hpp.
SLI_COUNT
template<size_t SLI = 5>
size_t dsa::TLSF< SLI >::SLI_COUNT = (1 << SL_INDEX_LOG2) [static], [constexpr], [private]
Definition at line 56 of file tlsf.hpp.
SMALL_BLOCK_SIZE
template<size_t SLI = 5>
size_t dsa::TLSF< SLI >::SMALL_BLOCK_SIZE = (1 << FL_INDEX_SHIFT) [static], [constexpr], [private]
Definition at line 59 of file tlsf.hpp.
The documentation for this class was generated from the following file:
src/tlsf.hpp