elock::LockGuard Class Reference
#include <globalLock.hpp>
Public Member Functions
LockGuard (ILockable &lock, uint32_t timeout_ms=0xFFFFFFFF)
~LockGuard ()
bool acquired () const
LockGuard (const LockGuard &)=delete
LockGuard & operator= (const LockGuard &)=delete
Private Attributes
ILockable & lock_
bool acquired_
Detailed Description
Definition at line 53 of file globalLock.hpp.
Constructor & Destructor Documentation
LockGuard() [1/2]
elock::LockGuard::LockGuard (ILockable & lock, uint32_t timeout_ms = 0xFFFFFFFF) [inline]
Definition at line 55 of file globalLock.hpp.
        : lock_(lock), acquired_(lock.lock(timeout_ms)) {}
References acquired_, and lock_.
Referenced by LockGuard(), and operator=().
~LockGuard()
elock::LockGuard::~LockGuard () [inline]
Definition at line 57 of file globalLock.hpp.
{ if (acquired_) lock_.unlock(); }
References acquired_, and lock_.
LockGuard() [2/2]
elock::LockGuard::LockGuard (const LockGuard &) [delete]
References LockGuard().
Member Function Documentation
acquired()
bool elock::LockGuard::acquired () const [inline]
Definition at line 58 of file globalLock.hpp.
{ return acquired_; }
References acquired_.
operator=()
LockGuard & elock::LockGuard::operator= (const LockGuard &) [delete]
References LockGuard().
Member Data Documentation
acquired_
bool elock::LockGuard::acquired_ [private]
Definition at line 63 of file globalLock.hpp.
Referenced by acquired(), LockGuard(), and ~LockGuard().
lock_
ILockable& elock::LockGuard::lock_ [private]
Definition at line 62 of file globalLock.hpp.
Referenced by LockGuard(), and ~LockGuard().
The documentation for this class was generated from the following file:
src/globalLock.hpp