LOG::Logger Class Reference
#include <Logger.hpp>
Public Types
using LogCallback = std::function<void(const char* tag, Level level, const char* message)>
Public Member Functions
void enable ()
void disable ()
void vlog (const char *tag, Level level, const char *format, va_list args)
void vlog (Level level, const char *format, va_list args)
void enableLevel (Level level)
void disableLevel (Level level)
bool isLevelEnabled (Level level) const
void blockTag (const char *tag)
void unblockTag (const char *tag)
bool isTagBlocked (const char *tag) const
void enableTimestamps (bool enable=true)
void disableTimestamps ()
void setLogCallback (LogCallback callback)
void setLevelColor (Level level, const char *color)
void setInfoAlternateColor (const char *color)
void setMinimumLevel (Level level)
Static Public Member Functions
static Logger & getInstance ()
Private Member Functions
Logger ()
void logInternal (const char *tag, Level level, const char *format, va_list args)
void processFormat (char *buffer, size_t bufferSize, const char *format, va_list args)
void formatBinary (char *buffer, size_t bufferSize, uint32_t value, int uppercase)
void buildModifiedFormat (char *modifiedFormat, size_t formatSize, const char *format, va_list args)
void handleBinaryFormat (char *buffer, size_t bufferSize, const char *format, va_list args)
const char * logLevelToString (Level level)
Logger (const Logger &)=delete
Logger & operator= (const Logger &)=delete
Private Attributes
bool enabled_
bool infoColorToggle_
const char * infoAlternateColor_
bool timestampEnabled_
Level minimumLevel_
std::bitset< 6 > enabledLevels_
std::array< const char *, 6 > levelColors_
std::unordered_set< std::string > blockedTags_
LogCallback logCallback_
Detailed Description
Definition at line 25 of file Logger.hpp.
Member Typedef Documentation
LogCallback
using LOG::Logger::LogCallback = std::function<void(const char* tag, Level level, const char* message)>
Definition at line 28 of file Logger.hpp.
Constructor & Destructor Documentation
Logger() [1/2]
LOG::Logger::Logger () [inline], [private]
Definition at line 73 of file Logger.hpp.
             :
        enabled_(true),
        infoColorToggle_(false),
        infoAlternateColor_("\033[1;34m"),
        minimumLevel_(Level::DEBUG),
        timestampEnabled_(false),
        levelColors_{
            "\033[1;37m", // DEBUG: bright white
            "\033[1;35m", // TEST: bright magenta
            "\033[1;36m", // INFO: bright cyan
            "\033[1;32m", // SUCCESS: bright green
            "\033[1;33m", // WARNING: bright yellow
            "\033[1;31m" // ERROR: bright red
        }
    {
        enabledLevels_.set(); // Enable all levels by default
    }
References LOG::DEBUG(), enabled_, enabledLevels_, infoAlternateColor_, infoColorToggle_, levelColors_, minimumLevel_, and timestampEnabled_.
Referenced by getInstance(), Logger(), and operator=().
Logger() [2/2]
LOG::Logger::Logger (const Logger &) [private], [delete]
References Logger().
Member Function Documentation
blockTag()
void LOG::Logger::blockTag (const char * tag) [inline]
Definition at line 59 of file Logger.hpp.
{ blockedTags_.insert(tag); }
References blockedTags_.
Referenced by LOG::BLOCK_TAG().
buildModifiedFormat()
void LOG::Logger::buildModifiedFormat (char * modifiedFormat, size_t formatSize, const char * format, va_list args) [inline], [private]
Definition at line 174 of file Logger.hpp.
    {
        size_t pos = 0;
        const char* current = format;
        while(*current && pos < formatSize - 1)
        {
            if(strncmp(current, "%b", 2) == 0 || strncmp(current, "%B", 2) == 0)
            {
                bool isUpperCase = (current[1] == 'B');
                uint32_t value = va_arg(args, uint32_t);
                char binaryBuffer[40];
                formatBinary(binaryBuffer, sizeof(binaryBuffer), value, isUpperCase);
                size_t binaryLen = strlen(binaryBuffer);
                if(pos + binaryLen >= formatSize - 1)
                {
                    binaryLen = formatSize - pos - 1;
                    binaryBuffer[binaryLen] = '\0';
                }
                strncpy(modifiedFormat + pos, binaryBuffer, binaryLen);
                pos += binaryLen;
                current += 2;
            }
            else
            {
                modifiedFormat[pos++] = *current++;
            }
        }
        modifiedFormat[pos] = '\0';
    }
References formatBinary().
Referenced by handleBinaryFormat().
disable()
void LOG::Logger::disable () [inline]
Definition at line 36 of file Logger.hpp.
{ enabled_ = false; }
References enabled_.
Referenced by LOG::DISABLE().
disableLevel()
void LOG::Logger::disableLevel (Level level) [inline]
Definition at line 54 of file Logger.hpp.
{ enabledLevels_.reset(static_cast<size_t>(level)); }
References enabledLevels_.
Referenced by LOG::DISABLE().
disableTimestamps()
void LOG::Logger::disableTimestamps () [inline]
Definition at line 63 of file Logger.hpp.
{ timestampEnabled_ = false; }
References timestampEnabled_.
Referenced by LOG::DISABLE_TIMESTAMPS().
enable()
void LOG::Logger::enable () [inline]
Definition at line 35 of file Logger.hpp.
{ enabled_ = true; }
References enabled_.
Referenced by LOG::ENABLE(), and enableTimestamps().
enableLevel()
void LOG::Logger::enableLevel (Level level) [inline]
Definition at line 53 of file Logger.hpp.
{ enabledLevels_.set(static_cast<size_t>(level)); }
References enabledLevels_.
Referenced by LOG::ENABLE().
enableTimestamps()
void LOG::Logger::enableTimestamps (bool enable = true) [inline]
Definition at line 62 of file Logger.hpp.
{ timestampEnabled_ = enable; }
References enable(), and timestampEnabled_.
Referenced by LOG::ENABLE_TIMESTAMPS().
formatBinary()
void LOG::Logger::formatBinary (char * buffer, size_t bufferSize, uint32_t value, int uppercase) [inline], [private]
Definition at line 139 of file Logger.hpp.
    {
        if(bufferSize < 2)
        {
            buffer[0] = '\0';
            return;
        }
        buffer[0] = '0';
        buffer[1] = uppercase ? 'B' : 'b';
        size_t pos = 2;
        uint32_t mask = 0x80000000;
        int started = 0;
        while(mask)
        {
            if(value & mask)
            {
                started = 1;
                buffer[pos++] = '1';
            }
            else if(started)
            {
                buffer[pos++] = '0';
            }
            if(pos >= bufferSize - 1)
            {
                break;
            }
            mask >>= 1;
        }
        if(!started && pos == 2)
        {
            buffer[pos++] = '0';
        }
        buffer[pos] = '\0';
    }
Referenced by buildModifiedFormat().
getInstance()
static Logger & LOG::Logger::getInstance () [inline], [static]
Definition at line 30 of file Logger.hpp.
    {
        static Logger instance;
        return instance;
    }
References Logger().
Referenced by LOG::BLOCK_TAG(), LOG::DEBUG(), LOG::DEBUG(), LOG::DISABLE(), LOG::DISABLE(), LOG::DISABLE_TIMESTAMPS(), LOG::ENABLE(), LOG::ENABLE(), LOG::ENABLE_TIMESTAMPS(), LOG::ERROR(), LOG::ERROR(), LOG::INFO(), LOG::INFO(), LOG::LOG_TEST(), LOG::LOG_TEST(), LOG::SUCCESS(), LOG::SUCCESS(), LOG::UNBLOCK_TAG(), LOG::WARNING(), and LOG::WARNING().
handleBinaryFormat()
void LOG::Logger::handleBinaryFormat (char * buffer, size_t bufferSize, const char * format, va_list args) [inline], [private]
Definition at line 204 of file Logger.hpp.
    {
        char modifiedFormat[LOG_BUFFER_SIZE];
        va_list argsCopy;
        va_copy(argsCopy, args);
        buildModifiedFormat(modifiedFormat, sizeof(modifiedFormat), format, argsCopy);
        va_end(argsCopy);
        vsnprintf(buffer, bufferSize, modifiedFormat, args);
    }
References buildModifiedFormat(), and LOG::LOG_BUFFER_SIZE.
Referenced by processFormat().
isLevelEnabled()
bool LOG::Logger::isLevelEnabled (Level level) const [inline]
Definition at line 55 of file Logger.hpp.
    {
        return enabledLevels_.test(static_cast<size_t>(level));
    }
References enabledLevels_.
Referenced by vlog(), and vlog().
isTagBlocked()
bool LOG::Logger::isTagBlocked (const char * tag) const [inline]
Definition at line 61 of file Logger.hpp.
{ return blockedTags_.count(tag); }
References blockedTags_.
logInternal()
void LOG::Logger::logInternal (const char * tag, Level level, const char * format, va_list args) [inline], [private]
Definition at line 99 of file Logger.hpp.
    {
        char messageBuffer[LOG_BUFFER_SIZE];
        processFormat(messageBuffer, sizeof(messageBuffer), format, args);
        const char* colorCode;
        if(level == Level::INFO)
        {
            colorCode =
                infoColorToggle_ ? infoAlternateColor_ : levelColors_[static_cast<size_t>(level)];
            infoColorToggle_ = !infoColorToggle_;
        }
        else
        {
            colorCode = levelColors_[static_cast<size_t>(level)];
        }
        const char* levelStr = logLevelToString(level);
        if(tag != nullptr)
        {
            printf("%s[%s][%s] %s\033[0m\n", colorCode, levelStr, tag, messageBuffer);
            if(logCallback_)
            {
                logCallback_(tag, level, messageBuffer);
            }
        }
        else
        {
            printf("%s[%s] %s\033[0m\n", colorCode, levelStr, messageBuffer);
        }
    }
References LOG::INFO, infoAlternateColor_, infoColorToggle_, levelColors_, LOG::LOG_BUFFER_SIZE, logCallback_, logLevelToString(), and processFormat().
Referenced by vlog(), and vlog().
logLevelToString()
const char * LOG::Logger::logLevelToString (Level level) [inline], [private]
Definition at line 213 of file Logger.hpp.
    {
        switch(level)
        {
            case Level::DEBUG:
                return "DEBUG";
            case Level::TEST:
                return "TEST";
            case Level::INFO:
                return "INFO";
            case Level::SUCCESS:
                return "SUCCESS";
            case Level::WARNING:
                return "WARNING";
            case Level::ERROR:
                return "ERROR";
            default:
                return "UNKNOWN";
        }
    }
References LOG::DEBUG, LOG::ERROR, LOG::INFO, LOG::SUCCESS, LOG::TEST, and LOG::WARNING.
Referenced by logInternal().
operator=()
Logger & LOG::Logger::operator= (const Logger &) [private], [delete]
References Logger().
processFormat()
void LOG::Logger::processFormat (char * buffer, size_t bufferSize, const char * format, va_list args) [inline], [private]
Definition at line 128 of file Logger.hpp.
    {
        if(strstr(format, "%b") || strstr(format, "%B"))
        {
            handleBinaryFormat(buffer, bufferSize, format, args);
        }
        else
        {
            vsnprintf(buffer, bufferSize, format, args);
        }
    }
References handleBinaryFormat().
Referenced by logInternal().
setInfoAlternateColor()
void LOG::Logger::setInfoAlternateColor (const char * color) [inline]
Definition at line 69 of file Logger.hpp.
{ infoAlternateColor_ = color; }
References infoAlternateColor_.
setLevelColor()
void LOG::Logger::setLevelColor (Level level, const char * color) [inline]
Definition at line 65 of file Logger.hpp.
    {
        levelColors_[static_cast<size_t>(level)] = color;
    }
References levelColors_.
setLogCallback()
void LOG::Logger::setLogCallback (LogCallback callback) [inline]
Definition at line 64 of file Logger.hpp.
{ logCallback_ = callback; }
References logCallback_.
setMinimumLevel()
void LOG::Logger::setMinimumLevel (Level level) [inline]
Definition at line 70 of file Logger.hpp.
{ minimumLevel_ = level; }
References minimumLevel_.
unblockTag()
void LOG::Logger::unblockTag (const char * tag) [inline]
Definition at line 60 of file Logger.hpp.
{ blockedTags_.erase(tag); }
References blockedTags_.
Referenced by LOG::UNBLOCK_TAG().
vlog() [1/2]
void LOG::Logger::vlog (const char * tag, Level level, const char * format, va_list args) [inline]
Definition at line 37 of file Logger.hpp.
    {
        if(!enabled_ || level < minimumLevel_ || !isLevelEnabled(level) || blockedTags_.count(tag))
        {
            return;
        }
        logInternal(tag, level, format, args);
    }
References blockedTags_, enabled_, isLevelEnabled(), logInternal(), and minimumLevel_.
Referenced by LOG::DEBUG(), LOG::DEBUG(), LOG::ERROR(), LOG::ERROR(), LOG::INFO(), LOG::INFO(), LOG::LOG_TEST(), LOG::LOG_TEST(), LOG::SUCCESS(), LOG::SUCCESS(), LOG::WARNING(), and LOG::WARNING().
vlog() [2/2]
void LOG::Logger::vlog (Level level, const char * format, va_list args) [inline]
Definition at line 45 of file Logger.hpp.
    {
        if(!enabled_ || level < minimumLevel_ || !isLevelEnabled(level))
        {
            return;
        }
        logInternal(nullptr, level, format, args);
    }
References enabled_, isLevelEnabled(), logInternal(), and minimumLevel_.
Member Data Documentation
blockedTags_
std::unordered_set<std::string> LOG::Logger::blockedTags_ [private]
Definition at line 97 of file Logger.hpp.
Referenced by blockTag(), isTagBlocked(), unblockTag(), and vlog().
enabled_
bool LOG::Logger::enabled_ [private]
Definition at line 90 of file Logger.hpp.
Referenced by disable(), enable(), Logger(), vlog(), and vlog().
enabledLevels_
std::bitset<6> LOG::Logger::enabledLevels_ [private]
Definition at line 95 of file Logger.hpp.
Referenced by disableLevel(), enableLevel(), isLevelEnabled(), and Logger().
infoAlternateColor_
const char* LOG::Logger::infoAlternateColor_ [private]
Definition at line 92 of file Logger.hpp.
Referenced by Logger(), logInternal(), and setInfoAlternateColor().
infoColorToggle_
bool LOG::Logger::infoColorToggle_ [private]
Definition at line 91 of file Logger.hpp.
Referenced by Logger(), and logInternal().
levelColors_
std::array<const char*, 6> LOG::Logger::levelColors_ [private]
Definition at line 96 of file Logger.hpp.
Referenced by Logger(), logInternal(), and setLevelColor().
logCallback_
LogCallback LOG::Logger::logCallback_ [private]
Definition at line 98 of file Logger.hpp.
Referenced by logInternal(), and setLogCallback().
minimumLevel_
Level LOG::Logger::minimumLevel_ [private]
Definition at line 94 of file Logger.hpp.
Referenced by Logger(), setMinimumLevel(), vlog(), and vlog().
timestampEnabled_
bool LOG::Logger::timestampEnabled_ [private]
Definition at line 93 of file Logger.hpp.
Referenced by disableTimestamps(), enableTimestamps(), and Logger().
The documentation for this class was generated from the following file:
src/Logger.hpp