Bit Manipulation Intrinsics
Functions
static int ffs (unsigned int word)
Find the first set bit in a word.
static int fls (unsigned int word)
Find the last set bit in a word.
static int fls_generic (unsigned int word)
Detailed Description
Function Documentation
ffs()
static int ffs (unsigned int word) [static]
#include <src/builtins.h>
Find the first set bit in a word.
Returns the position of the first set bit (1-based index) in the given word. If the word is zero, returns -1.
Parameters
word The input word to scan.
Returns
The position of the first set bit, or -1 if the word is zero.
Definition at line 146 of file builtins.h.
                                    {
  return fls_generic(word & (~word + 1)) - 1;
}
References dsa_decl, and fls_generic().
Referenced by dsa::TLSF< 5 >::search_suitable_block().
fls()
static int fls (unsigned int word) [static]
#include <src/builtins.h>
Find the last set bit in a word.
Returns the position of the last set bit (1-based index) in the given word. If the word is zero, returns -1.
Parameters
word The input word to scan.
Returns
The position of the last set bit, or -1 if the word is zero.
Definition at line 150 of file builtins.h.
{ return fls_generic(word) - 1; }
References dsa_decl, and fls_generic().
Referenced by dsa::TLSF< 5 >::mapping_insert(), and dsa::TLSF< 5 >::mapping_search().
fls_generic()
static int fls_generic (unsigned int word) [static]
#include <src/builtins.h>
Definition at line 116 of file builtins.h.
                                            {
  int bit = 32;
  if (!word)
    bit -= 1;
  if (!(word & 0xffff0000)) {
    word <<= 16;
    bit -= 16;
  }
  if (!(word & 0xff000000)) {
    word <<= 8;
    bit -= 8;
  }
  if (!(word & 0xf0000000)) {
    word <<= 4;
    bit -= 4;
  }
  if (!(word & 0xc0000000)) {
    word <<= 2;
    bit -= 2;
  }
  if (!(word & 0x80000000)) {
    word <<= 1;
    bit -= 1;
  }
  return bit;
}
References dsa_decl.
Referenced by ffs(), and fls().