LOG Namespace Reference
Classes
class Logger
Enumerations
enum class Level {
DEBUG = 0
, TEST = 1
, INFO = 2
, SUCCESS = 3
,
WARNING = 4
, ERROR = 5
 }
Functions
static void DEBUG (const char *tag, const char *format,...)
static void DEBUG (const char *format,...)
static void LOG_TEST (const char *tag, const char *format,...)
static void LOG_TEST (const char *format,...)
static void INFO (const char *tag, const char *format,...)
static void INFO (const char *format,...)
static void SUCCESS (const char *tag, const char *format,...)
static void SUCCESS (const char *format,...)
static void WARNING (const char *tag, const char *format,...)
static void WARNING (const char *format,...)
static void ERROR (const char *tag, const char *format,...)
static void ERROR (const char *format,...)
static void ENABLE ()
static void ENABLE (Level level)
static void DISABLE ()
static void DISABLE (Level level)
static void BLOCK_TAG (const char *tag)
static void UNBLOCK_TAG (const char *tag)
static void ENABLE_TIMESTAMPS ()
static void DISABLE_TIMESTAMPS ()
Variables
static constexpr uint16_t LOG_BUFFER_SIZE = 256
Enumeration Type Documentation
Level
enum class LOG::Level [strong]
Enumerator
DEBUG
TEST
INFO
SUCCESS
WARNING
ERROR
Definition at line 16 of file Logger.hpp.
                 {
    DEBUG = 0, // Lowest priority (most verbose)
    TEST = 1,
    INFO = 2,
    SUCCESS = 3,
    WARNING = 4,
    ERROR = 5 // Highest priority (least verbose)
};
Function Documentation
BLOCK_TAG()
static void LOG::BLOCK_TAG (const char * tag) [inline], [static]
Definition at line 330 of file Logger.hpp.
{ Logger::getInstance().blockTag(tag); }
References LOG::Logger::blockTag(), and LOG::Logger::getInstance().
DEBUG() [1/2]
static void LOG::DEBUG (const char * format, ...) [inline], [static]
Definition at line 245 of file Logger.hpp.
{
    va_list args;
    va_start(args, format);
    Logger::getInstance().vlog(Level::DEBUG, format, args);
    va_end(args);
}
References DEBUG, LOG::Logger::getInstance(), and LOG::Logger::vlog().
DEBUG() [2/2]
static void LOG::DEBUG (const char * tag, const char * format, ...) [inline], [static]
Definition at line 238 of file Logger.hpp.
{
    va_list args;
    va_start(args, format);
    Logger::getInstance().vlog(tag, Level::DEBUG, format, args);
    va_end(args);
}
References DEBUG, LOG::Logger::getInstance(), and LOG::Logger::vlog().
Referenced by LOG::Logger::Logger().
DISABLE() [1/2]
static void LOG::DISABLE () [inline], [static]
Definition at line 328 of file Logger.hpp.
{ Logger::getInstance().disable(); }
References LOG::Logger::disable(), and LOG::Logger::getInstance().
DISABLE() [2/2]
static void LOG::DISABLE (Level level) [inline], [static]
Definition at line 329 of file Logger.hpp.
{ Logger::getInstance().disableLevel(level); }
References LOG::Logger::disableLevel(), and LOG::Logger::getInstance().
DISABLE_TIMESTAMPS()
static void LOG::DISABLE_TIMESTAMPS () [inline], [static]
Definition at line 337 of file Logger.hpp.
{ Logger::getInstance().disableTimestamps(); }
References LOG::Logger::disableTimestamps(), and LOG::Logger::getInstance().
ENABLE() [1/2]
static void LOG::ENABLE () [inline], [static]
Definition at line 322 of file Logger.hpp.
{ Logger::getInstance().enable(); }
References LOG::Logger::enable(), and LOG::Logger::getInstance().
Referenced by ENABLE(), and ENABLE_TIMESTAMPS().
ENABLE() [2/2]
static void LOG::ENABLE (Level level) [inline], [static]
Definition at line 323 of file Logger.hpp.
{
    ENABLE();
    Logger::getInstance().enableLevel(level);
}
References ENABLE(), LOG::Logger::enableLevel(), and LOG::Logger::getInstance().
ENABLE_TIMESTAMPS()
static void LOG::ENABLE_TIMESTAMPS () [inline], [static]
Definition at line 332 of file Logger.hpp.
{
    ENABLE();
    Logger::getInstance().enableTimestamps(true);
}
References ENABLE(), LOG::Logger::enableTimestamps(), and LOG::Logger::getInstance().
ERROR() [1/2]
static void LOG::ERROR (const char * format, ...) [inline], [static]
Definition at line 315 of file Logger.hpp.
{
    va_list args;
    va_start(args, format);
    Logger::getInstance().vlog(Level::ERROR, format, args);
    va_end(args);
}
References ERROR, LOG::Logger::getInstance(), and LOG::Logger::vlog().
ERROR() [2/2]
static void LOG::ERROR (const char * tag, const char * format, ...) [inline], [static]
Definition at line 308 of file Logger.hpp.
{
    va_list args;
    va_start(args, format);
    Logger::getInstance().vlog(tag, Level::ERROR, format, args);
    va_end(args);
}
References ERROR, LOG::Logger::getInstance(), and LOG::Logger::vlog().
INFO() [1/2]
static void LOG::INFO (const char * format, ...) [inline], [static]
Definition at line 273 of file Logger.hpp.
{
    va_list args;
    va_start(args, format);
    Logger::getInstance().vlog(Level::INFO, format, args);
    va_end(args);
}
References LOG::Logger::getInstance(), INFO, and LOG::Logger::vlog().
INFO() [2/2]
static void LOG::INFO (const char * tag, const char * format, ...) [inline], [static]
Definition at line 266 of file Logger.hpp.
{
    va_list args;
    va_start(args, format);
    Logger::getInstance().vlog(tag, Level::INFO, format, args);
    va_end(args);
}
References LOG::Logger::getInstance(), INFO, and LOG::Logger::vlog().
LOG_TEST() [1/2]
static void LOG::LOG_TEST (const char * format, ...) [inline], [static]
Definition at line 259 of file Logger.hpp.
{
    va_list args;
    va_start(args, format);
    Logger::getInstance().vlog(Level::TEST, format, args);
    va_end(args);
}
References LOG::Logger::getInstance(), TEST, and LOG::Logger::vlog().
LOG_TEST() [2/2]
static void LOG::LOG_TEST (const char * tag, const char * format, ...) [inline], [static]
Definition at line 252 of file Logger.hpp.
{
    va_list args;
    va_start(args, format);
    Logger::getInstance().vlog(tag, Level::TEST, format, args);
    va_end(args);
}
References LOG::Logger::getInstance(), TEST, and LOG::Logger::vlog().
SUCCESS() [1/2]
static void LOG::SUCCESS (const char * format, ...) [inline], [static]
Definition at line 287 of file Logger.hpp.
{
    va_list args;
    va_start(args, format);
    Logger::getInstance().vlog(Level::SUCCESS, format, args);
    va_end(args);
}
References LOG::Logger::getInstance(), SUCCESS, and LOG::Logger::vlog().
SUCCESS() [2/2]
static void LOG::SUCCESS (const char * tag, const char * format, ...) [inline], [static]
Definition at line 280 of file Logger.hpp.
{
    va_list args;
    va_start(args, format);
    Logger::getInstance().vlog(tag, Level::SUCCESS, format, args);
    va_end(args);
}
References LOG::Logger::getInstance(), SUCCESS, and LOG::Logger::vlog().
UNBLOCK_TAG()
static void LOG::UNBLOCK_TAG (const char * tag) [inline], [static]
Definition at line 331 of file Logger.hpp.
{ Logger::getInstance().unblockTag(tag); }
References LOG::Logger::getInstance(), and LOG::Logger::unblockTag().
WARNING() [1/2]
static void LOG::WARNING (const char * format, ...) [inline], [static]
Definition at line 301 of file Logger.hpp.
{
    va_list args;
    va_start(args, format);
    Logger::getInstance().vlog(Level::WARNING, format, args);
    va_end(args);
}
References LOG::Logger::getInstance(), LOG::Logger::vlog(), and WARNING.
WARNING() [2/2]
static void LOG::WARNING (const char * tag, const char * format, ...) [inline], [static]
Definition at line 294 of file Logger.hpp.
{
    va_list args;
    va_start(args, format);
    Logger::getInstance().vlog(tag, Level::WARNING, format, args);
    va_end(args);
}
References LOG::Logger::getInstance(), LOG::Logger::vlog(), and WARNING.
Variable Documentation
LOG_BUFFER_SIZE
uint16_t LOG::LOG_BUFFER_SIZE = 256 [static], [constexpr]
Definition at line 15 of file Logger.hpp.
Referenced by LOG::Logger::handleBinaryFormat(), and LOG::Logger::logInternal().